ingressController:
  enabled: false
  installCRDs: false
  image: 
    repository: kong/kubernetes-ingress-controller 
    tag: 2.0.1
image:
  repository: kong/kong-gateway
  tag: 2.8-alpine 
secretVolumes:
- kong-cluster-cert
env:
  database: postgres
  role: control_plane
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  pg_host: kong-postgresql.kong.svc.cluster.local
cluster:
  enabled: true
  volumePermissions: 
    enabled: true
  tls:
    enabled: true
    servicePort: 8005
    containerPort: 8005
clustertelemetry:
  enabled: true
  tls:
    enabled: true
    servicePort: 8006
    containerPort: 8006
proxy:
  enabled: false
admin:
  enabled: true
  http:
    enabled: true
  type: LoadBalancer
manager: 
  enabled: true
  type: LoadBalancer
postgresql: 
  enabled: true 
  image:
    tag: 11.17.0
  volumePermissions:
    enabled: true
  #host: kong-postgres.kong.svc.cluster.local
  auth:
    username: kong
    database: kong
    password: kong
enterprise: 
  enabled: true